import { TOTAL_REWARD_INITIAL_CYCLE } from ".";

export const MINING_REWARD = 135 / TOTAL_REWARD_INITIAL_CYCLE;
export const COMMUNITY_FUND = 19.9 / TOTAL_REWARD_INITIAL_CYCLE;
export const ANCHOR_REWARD = 0.1 / TOTAL_REWARD_INITIAL_CYCLE;
export const DEX_LIQUIDTY_MINING = 103.1 / TOTAL_REWARD_INITIAL_CYCLE;
export const ATOMIC_SWAP_INCENTIVES = 50 / TOTAL_REWARD_INITIAL_CYCLE;
export const FUTURES_INCENTIVES = 50 / TOTAL_REWARD_INITIAL_CYCLE;
export const OPTIONS_INCENTIVES = 40 / TOTAL_REWARD_INITIAL_CYCLE;
export const UNALLOCATED_INCENTIVES = 6.94 / TOTAL_REWARD_INITIAL_CYCLE;
